version: '3.8'
services:
  imgupload:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/imgupload
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=oussa
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=oussa
      - MYSQL_PASSWORD=oussa
      - MYSQL_DATABASE=imgupload
    volumes:
      - imgupload_mysql_data:/var/lib/mysql
      - imgupload_mysql_config:/etc/mysql/conf.d
volumes:
  imgupload_mysql_data:
  imgupload_mysql_config:

